# Generated by Django 2.2.1 on 2019-05-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_url', models.URLField(default='https://mbasic.facebook.com')),
                ('current_city', models.CharField(blank=True, max_length=250, null=True)),
                ('hometown', models.CharField(blank=True, max_length=250, null=True)),
                ('friend_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friends', to='core.Account')),
            ],
        ),
    ]
