# Generated by Django 2.2.1 on 2019-05-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190522_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friends', to='core.Account'),
        ),
    ]
